//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddtoCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbproduct
    {
        public int id { get; set; }
        public string p_name { get; set; }
        public Nullable<int> p_price { get; set; }
        public string pimage { get; set; }
        public Nullable<int> pcategory { get; set; }
        public Nullable<int> pbrand { get; set; }
        public string pdescription { get; set; }
        public Nullable<System.DateTime> pEntry { get; set; }
    
        public virtual tbbrand tbbrand { get; set; }
        public virtual tbcat tbcat { get; set; }
    }
}
